name: Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  lint:
  name: Lint code
  runs-on: ubuntu-latest

  steps:
    - name: Install Golang
      uses: actions/setup-go@v2
      with:
        go-version: "~1.15"

    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Go vet
      run: go vet .

    - name: Go lint
      run: golint .
